// src/utils/mockData.js
const blogPost = [
    {
      id: 1,
      title: "Exploring Styled-Components",
      author: "Jane Doe",
      date: "August 20, 2024",
      content: "Styled-components is a library for React and React Native that allows you to use component-level styles in your application...",
      slug: "exploring-styled-components",
      imageUrl: "https://images.unsplash.com/photo-1502865787650-3f8318917153?w=400&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1yZWxhdGVkfDEwfHx8ZW58MHx8fHx8",
    },
    {
      id: 2,
      title: "Understanding React Hooks",
      author: "John Smith",
      date: "August 21, 2024",
      content: "React Hooks are functions that let you use state and other React features without writing a class...",
      slug: "understanding-react-hooks",
      imageUrl: "https://images.unsplash.com/photo-1502865787650-3f8318917153?w=400&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1yZWxhdGVkfDEwfHx8ZW58MHx8fHx8",
    },
    {
      id: 3,
      title: "Getting Started with TypeScript",
      author: "Alice Johnson",
      date: "August 22, 2024",
      content: "TypeScript is a typed superset of JavaScript that compiles to plain JavaScript...",
      slug: "getting-started-with-typescript",
      imageUrl: "https://plus.unsplash.com/premium_photo-1663926032186-2b4df6a39b10?w=400&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1yZWxhdGVkfDEyfHx8ZW58MHx8fHx8",
    },
    {
      id: 4,
      title: "Building Reusable Components",
      author: "Bob Brown",
      date: "August 23, 2024",
      content: "Reusable components are at the core of React's philosophy...",
      slug: "building-reusable-components",
      imageUrl: "https://plus.unsplash.com/premium_photo-1663926032186-2b4df6a39b10?w=400&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1yZWxhdGVkfDEyfHx8ZW58MHx8fHx8",
    },
    {
      id: 5,
      title: "Advanced State Management with Redux",
      author: "Susan Davis",
      date: "August 24, 2024",
      content: "Redux is a predictable state container for JavaScript apps...",
      slug: "advanced-state-management-with-redux",
      imageUrl: "https://images.unsplash.com/photo-1651256785597-4efe48fd71f9?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTZ8fHJlY2lwZXN8ZW58MHx8MHx8fDA%3D",
    },
    {
      id: 6,
      title: "Introduction to GraphQL",
      author: "Michael Scott",
      date: "August 25, 2024",
      content: "GraphQL is a query language for APIs that allows clients to request only the data they need...",
      slug: "introduction-to-graphql",
      imageUrl: "https://images.unsplash.com/photo-1590616270818-f08142f85c6b?w=400&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1yZWxhdGVkfDE3fHx8ZW58MHx8fHx8",
    },
    {
      id: 7,
      title: "Exploring Functional Programming",
      author: "Emma Wilson",
      date: "August 26, 2024",
      content: "Functional programming is a programming paradigm that treats computation as the evaluation of mathematical functions...",
      slug: "exploring-functional-programming",
      imageUrl: "https://images.unsplash.com/photo-1590616270818-f08142f85c6b?w=400&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1yZWxhdGVkfDE3fHx8ZW58MHx8fHx8",
    },
    {
      id: 8,
      title: "The Power of CSS Grid",
      author: "Liam Martinez",
      date: "August 27, 2024",
      content: "CSS Grid Layout is a two-dimensional layout system for the web...",
      slug: "the-power-of-css-grid",
      imageUrl: "https://images.unsplash.com/photo-1515543237350-b3eea1ec8082?w=400&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1yZWxhdGVkfDE1fHx8ZW58MHx8fHx8",
    },
    {
      id: 9,
      title: "Mastering Flexbox",
      author: "Olivia Garcia",
      date: "August 28, 2024",
      content: "Flexbox is a one-dimensional layout method for laying out items in rows or columns...",
      slug: "mastering-flexbox",
      imageUrl: "https://images.unsplash.com/photo-1515543237350-b3eea1ec8082?w=400&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1yZWxhdGVkfDE1fHx8ZW58MHx8fHx8",
    },
    {
      id: 10,
      title: "Understanding Asynchronous JavaScript",
      author: "James Wilson",
      date: "August 29, 2024",
      content: "Asynchronous JavaScript is the backbone of modern web development...",
      slug: "understanding-asynchronous-javascript",
      imageUrl: "https://plus.unsplash.com/premium_photo-1723734018681-5572d446659c?w=400&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1yZWxhdGVkfDE2fHx8ZW58MHx8fHx8",
    },
    {
      id: 11,
      title: "Optimizing Web Performance",
      author: "Ella Brown",
      date: "August 30, 2024",
      content: "Web performance is about making websites fast, including making slow processes run faster...",
      slug: "optimizing-web-performance",
      imageUrl: "https://images.unsplash.com/photo-1609767999050-dfd2185aaf7f?w=400&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1yZWxhdGVkfDEzfHx8ZW58MHx8fHx8",
    },
    {
      id: 12,
      title: "Deploying Applications with Docker",
      author: "William Thompson",
      date: "August 31, 2024",
      content: "Docker is an open platform for developing, shipping, and running applications...",
      slug: "deploying-applications-with-docker",
      imageUrl: "https://images.unsplash.com/photo-1609767999050-dfd2185aaf7f?w=400&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1yZWxhdGVkfDEzfHx8ZW58MHx8fHx8",
    },
    {
      id: 13,
      title: "Continuous Integration with Jenkins",
      author: "Ava White",
      date: "September 1, 2024",
      content: "Continuous Integration (CI) is a development practice where developers integrate code into a shared repository frequently...",
      slug: "continuous-integration-with-jenkins",
      imageUrl: "https://images.unsplash.com/photo-1651256785597-4efe48fd71f9?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTZ8fHJlY2lwZXN8ZW58MHx8MHx8fDA%3D",
    },
    {
      id: 14,
      title: "Introduction to Machine Learning",
      author: "Mia Anderson",
      date: "September 2, 2024",
      content: "Machine learning is a method of data analysis that automates analytical model building...",
      slug: "introduction-to-machine-learning",
      imageUrl: "https://images.unsplash.com/photo-1651256785597-4efe48fd71f9?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTZ8fHJlY2lwZXN8ZW58MHx8MHx8fDA%3D",
    },
    {
      id: 15,
      title: "Getting Started with Python",
      author: "Lucas Martinez",
      date: "September 3, 2024",
      content: "Python is an interpreted, high-level, general-purpose programming language...",
      slug: "getting-started-with-python",
      imageUrl: "https://media.istockphoto.com/id/1481308773/photo/delicious-salad-with-arugula-radicchio-peaches-prosciutto-feta-cheese-and-blueberries-black.webp?b=1&s=612x612&w=0&k=20&c=5OFcMTEZ8H6hkK4WBg_GX1Rqm2x_zotjr7U7h1an_IA=",
    },
    {
      id: 16,
      title: "Building RESTful APIs with Node.js",
      author: "Sophia Clark",
      date: "September 4, 2024",
      content: "Node.js is an open-source, cross-platform, JavaScript runtime environment that executes JavaScript code outside a web browser...",
      slug: "building-restful-apis-with-nodejs",
      imageUrl: "https://media.istockphoto.com/id/1481308773/photo/delicious-salad-with-arugula-radicchio-peaches-prosciutto-feta-cheese-and-blueberries-black.webp?b=1&s=612x612&w=0&k=20&c=5OFcMTEZ8H6hkK4WBg_GX1Rqm2x_zotjr7U7h1an_IA=",
    },
    {
      id: 17,
      title: "Introduction to Kubernetes",
      author: "Mason Lee",
      date: "September 5, 2024",
      content: "Kubernetes is an open-source container-orchestration system for automating computer application deployment, scaling, and management...",
      slug: "introduction-to-kubernetes",
      imageUrl: "https://media.istockphoto.com/id/1361367886/photo/female-food-blogger-preparing-pizza-and-recording-video-on-smart-phone.webp?b=1&s=612x612&w=0&k=20&c=hxwe1H692j6gUgyhoiFfQhg_iObQKU_2VJOshXzgKyI=",
    },
    {
      id: 18,
      title: "Understanding Microservices Architecture",
      author: "Isabella Walker",
      date: "September 6, 2024",
      content: "Microservices are an architectural style that structures an application as a collection of services...",
      slug: "understanding-microservices-architecture",
      imageUrl: "https://media.istockphoto.com/id/1361367886/photo/female-food-blogger-preparing-pizza-and-recording-video-on-smart-phone.webp?b=1&s=612x612&w=0&k=20&c=hxwe1H692j6gUgyhoiFfQhg_iObQKU_2VJOshXzgKyI=",
    },
    {
      id: 19,
      title: "Getting Started with DevOps",
      author: "Logan Perez",
      date: "September 7, 2024",
      content: "DevOps is a set of practices that combines software development (Dev) and IT operations (Ops)...",
      slug: "getting-started-with-devops",
      imageUrl: "https://media.istockphoto.com/id/1389630335/photo/vegan-carrot-salad-on-a-rustic-bacground.webp?b=1&s=612x612&w=0&k=20&c=hJUxusfDzckZ8S1wdn7P1roR0gz0dsEiDUv-P2aLMNs=",
    },
    {
      id: 20,
      title: "Exploring Serverless Architecture",
      author: "Charlotte Hall",
      date: "September 8, 2024",
      content: "Serverless computing is a cloud-computing execution model in which the cloud provider runs the server, and dynamically manages the allocation of machine resources...",
      slug: "exploring-serverless-architecture",
      imageUrl: "https://media.istockphoto.com/id/1389630335/photo/vegan-carrot-salad-on-a-rustic-bacground.webp?b=1&s=612x612&w=0&k=20&c=hJUxusfDzckZ8S1wdn7P1roR0gz0dsEiDUv-P2aLMNs=",
    },
    {
      id: 21,
      title: "Building a Scalable Backend with AWS",
      author: "Benjamin Young",
      date: "September 9, 2024",
      content: "Amazon Web Services (AWS) is a subsidiary of Amazon providing on-demand cloud computing platforms and APIs to individuals, companies, and governments...",
      slug: "building-scalable-backend-with-aws",
      imageUrl: "https://source.unsplash.com/random/400x200?aws",
    },
    {
      id: 22,
      title: "Introduction to Cloud Computing",
      author: "Harper Hernandez",
      date: "September 10, 2024",
      content: "Cloud computing is the on-demand availability of computer system resources, especially data storage and computing power, without direct active management by the user...",
      slug: "introduction-to-cloud-computing",
      imageUrl: "https://source.unsplash.com/random/400x200?cloud-computing",
    },
    {
      id: 23,
      title: "Understanding RESTful Services",
      author: "Sebastian King",
      date: "September 11, 2024",
      content: "REST (Representational State Transfer) is a software architectural style that defines a set of constraints to be used for creating Web services...",
      slug: "understanding-restful-services",
      imageUrl: "https://source.unsplash.com/random/400x200?rest-api",
    },
    {
      id: 24,
      title: "Getting Started with JavaScript ES6",
      author: "Zoe Wright",
      date: "September 12, 2024",
      content: "ECMAScript 6 (ES6) is a major update to JavaScript that includes dozens of new features...",
      slug: "getting-started-with-javascript-es6",
      imageUrl: "https://source.unsplash.com/random/400x200?javascript",
    },
    {
      id: 25,
      title: "Building a Full-Stack App with MERN",
      author: "Elijah Robinson",
      date: "September 13, 2024",
      content: "MERN stack is a JavaScript stack that's designed to make the development process smoother...",
      slug: "building-full-stack-app-with-mern",
      imageUrl: "https://source.unsplash.com/random/400x200?mern-stack",
    },
    {
      id: 26,
      title: "Introduction to Web Accessibility",
      author: "Avery Carter",
      date: "September 14, 2024",
      content: "Web accessibility refers to the inclusive practice of removing barriers that prevent interaction with, or access to, websites by people with disabilities...",
      slug: "introduction-to-web-accessibility",
      imageUrl: "https://source.unsplash.com/random/400x200?accessibility",
    },
    {
      id: 27,
      title: "Mastering CSS Animations",
      author: "Daniel Mitchell",
      date: "September 15, 2024",
      content: "CSS animations make it possible to animate transitions from one CSS style configuration to another...",
      slug: "mastering-css-animations",
      imageUrl: "https://source.unsplash.com/random/400x200?css-animations",
    },
    {
      id: 28,
      title: "Exploring the JAMstack",
      author: "Lily Roberts",
      date: "September 16, 2024",
      content: "JAMstack is a modern web development architecture based on client-side JavaScript, reusable APIs, and prebuilt Markup...",
      slug: "exploring-the-jamstack",
      imageUrl: "https://source.unsplash.com/random/400x200?jamstack",
    },
    {
      id: 29,
      title: "Getting Started with Webpack",
      author: "Henry Lewis",
      date: "September 17, 2024",
      content: "Webpack is an open-source JavaScript module bundler...",
      slug: "getting-started-with-webpack",
      imageUrl: "https://source.unsplash.com/random/400x200?webpack",
    },
    {
      id: 30,
      title: "Mastering React Testing Library",
      author: "Evelyn Lee",
      date: "September 18, 2024",
      content: "React Testing Library is a set of helpers that let you test React components without relying on their implementation details...",
      slug: "mastering-react-testing-library",
      imageUrl: "https://source.unsplash.com/random/400x200?testing-library",
    },
    {
      id: 31,
      title: "Understanding JavaScript Promises",
      author: "Grace Harris",
      date: "September 19, 2024",
      content: "A promise is an object representing the eventual completion or failure of an asynchronous operation...",
      slug: "understanding-javascript-promises",
      imageUrl: "https://source.unsplash.com/random/400x200?promises",
    },
    {
      id: 32,
      title: "Exploring CSS Variables",
      author: "Samuel Nelson",
      date: "September 20, 2024",
      content: "CSS Variables are entities defined by CSS authors that contain specific values to be reused throughout a document...",
      slug: "exploring-css-variables",
      imageUrl: "https://source.unsplash.com/random/400x200?css-variables",
    },
    {
      id: 33,
      title: "Introduction to Progressive Web Apps",
      author: "Harper Scott",
      date: "September 21, 2024",
      content: "Progressive Web Apps (PWAs) are web applications that have been designed so they are capable, reliable, and installable...",
      slug: "introduction-to-progressive-web-apps",
      imageUrl: "https://source.unsplash.com/random/400x200?pwa",
    },
    {
      id: 34,
      title: "Building a Modern Frontend with React",
      author: "Chloe Adams",
      date: "September 22, 2024",
      content: "React is a JavaScript library for building user interfaces. It is maintained by Facebook and a community of individual developers and companies...",
      slug: "building-modern-frontend-with-react",
      imageUrl: "https://source.unsplash.com/random/400x200?react",
    },
    {
      id: 35,
      title: "Understanding the Virtual DOM",
      author: "Jack Rivera",
      date: "September 23, 2024",
      content: "The virtual DOM (VDOM) is a programming concept where an ideal, or 'virtual', representation of a UI is kept in memory and synced with the 'real' DOM by a library such as React...",
      slug: "understanding-virtual-dom",
      imageUrl: "https://source.unsplash.com/random/400x200?dom",
    },
    {
      id: 36,
      title: "Exploring Responsive Design",
      author: "Abigail Stewart",
      date: "September 24, 2024",
      content: "Responsive web design is an approach to web design that makes web pages render well on a variety of devices and window or screen sizes...",
      slug: "exploring-responsive-design",
      imageUrl: "https://source.unsplash.com/random/400x200?responsive",
    },
    {
      id: 37,
      title: "Introduction to Design Systems",
      author: "Leo Simmons",
      date: "September 25, 2024",
      content: "A design system is a collection of reusable components, guided by clear standards, that can be assembled together to build any number of applications...",
      slug: "introduction-to-design-systems",
      imageUrl: "https://source.unsplash.com/random/400x200?design-system",
    },
    {
      id: 38,
      title: "Mastering CSS Flexbox",
      author: "Sophie Clark",
      date: "September 26, 2024",
      content: "Flexbox is a one-dimensional layout method for laying out items in rows or columns...",
      slug: "mastering-css-flexbox",
      imageUrl: "https://source.unsplash.com/random/400x200?flexbox",
    },
    {
      id: 39,
      title: "Building Dynamic User Interfaces with React",
      author: "Aiden Rogers",
      date: "September 27, 2024",
      content: "React's component-based architecture makes it easy to build dynamic user interfaces that respond to user interactions...",
      slug: "building-dynamic-interfaces-with-react",
      imageUrl: "https://source.unsplash.com/random/400x200?react-ui",
    },
    {
      id: 40,
      title: "Exploring the Node.js Ecosystem",
      author: "Scarlett Hill",
      date: "September 28, 2024",
      content: "The Node.js ecosystem is vast and full of powerful tools and libraries that can help you build high-performance applications...",
      slug: "exploring-nodejs-ecosystem",
      imageUrl: "https://images.unsplash.com/photo-1598514983195-94d7470a4241?w=400&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1yZWxhdGVkfDE5fHx8ZW58MHx8fHx8",
    },
    {
      id: 41,
      title: "Understanding the Event Loop in JavaScript",
      author: "Eleanor Campbell",
      date: "September 29, 2024",
      content: "The event loop is what allows JavaScript to perform non-blocking I/O operations...",
      slug: "understanding-event-loop",
      imageUrl: "https://images.unsplash.com/photo-1598514983195-94d7470a4241?w=400&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1yZWxhdGVkfDE5fHx8ZW58MHx8fHx8",
    },
    {
      id: 42,
      title: "Introduction to WebSockets",
      author: "Gabriel Martinez",
      date: "September 30, 2024",
      content: "WebSockets are a protocol that provides full-duplex communication channels over a single TCP connection...",
      slug: "introduction-to-websockets",
      imageUrl: "https://plus.unsplash.com/premium_photo-1704989936092-c41f477cb6e2?w=400&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1yZWxhdGVkfDIwfHx8ZW58MHx8fHx8",
    },
    {
      id: 43,
      title: "Building Real-Time Applications",
      author: "Victoria Turner",
      date: "October 1, 2024",
      content: "Real-time web applications enable the seamless transmission of data between the server and client...",
      slug: "building-real-time-applications",
      imageUrl: "https://plus.unsplash.com/premium_photo-1704989936092-c41f477cb6e2?w=400&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1yZWxhdGVkfDIwfHx8ZW58MHx8fHx8",
    },
    {
      id: 44,
      title: "Exploring the GraphQL Query Language",
      author: "Isaac Collins",
      date: "October 2, 2024",
      content: "GraphQL is a query language for APIs and a runtime for executing those queries by using a type system you define for your data...",
      slug: "exploring-graphql-query-language",
      imageUrl: "https://images.unsplash.com/photo-1562923690-e274ba919781?q=80&w=476&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    },
    {
      id: 45,
      title: "Understanding API Rate Limiting",
      author: "Isla Morales",
      date: "October 3, 2024",
      content: "Rate limiting is a technique used to control the rate at which an API is consumed...",
      slug: "understanding-api-rate-limiting",
      imageUrl: "https://images.unsplash.com/photo-1562923690-e274ba919781?q=80&w=476&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    },
    {
      id: 46,
      title: "Introduction to Headless CMS",
      author: "Hannah Bell",
      date: "October 4, 2024",
      content: "A headless CMS is a content management system that allows content to be delivered via an API, separating the content repository from the front-end...",
      slug: "introduction-to-headless-cms",
      imageUrl: "https://plus.unsplash.com/premium_photo-1683707120330-603d9963cb02?w=1000&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NXx8cmVjaXBlc3xlbnwwfHwwfHx8MA%3D%3D",
    },
    {
      id: 47,
      title: "Getting Started with DevOps",
      author: "Andrew Cooper",
      date: "October 5, 2024",
      content: "DevOps is a set of practices that combines software development (Dev) and IT operations (Ops)...",
      slug: "getting-started-with-devops",
      imageUrl: "https://plus.unsplash.com/premium_photo-1683707120330-603d9963cb02?w=1000&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NXx8cmVjaXBlc3xlbnwwfHwwfHx8MA%3D%3D",
    },
    {
      id: 48,
      title: "Mastering JavaScript Closures",
      author: "Natalie King",
      date: "October 6, 2024",
      content: "A closure is a function that has access to its own scope, the scope of the outer function, and the global scope...",
      slug: "mastering-javascript-closures",
      imageUrl: "https://images.unsplash.com/photo-1566312235254-d4b52d8fb053?w=1000&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NHx8cmVjaXBlc3xlbnwwfHwwfHx8MA%3D%3D",
    },
    {
      id: 49,
      title: "Exploring the Vue.js Framework",
      author: "Owen Scott",
      date: "October 7, 2024",
      content: "Vue.js is a progressive framework for building user interfaces...",
      slug: "exploring-vuejs-framework",
      imageUrl: "https://images.unsplash.com/photo-1566312235254-d4b52d8fb053?w=1000&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NHx8cmVjaXBlc3xlbnwwfHwwfHx8MA%3D%3D",
    },
    {
      id: 50,
      title: "Understanding Dependency Injection",
      author: "Emma Jenkins",
      date: "October 8, 2024",
      content: "Dependency injection is a design pattern used to implement IoC (Inversion of Control), allowing for better modularization of code...",
      slug: "understanding-dependency-injection",
      imageUrl: "https://images.unsplash.com/photo-1566312235254-d4b52d8fb053?w=1000&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NHx8cmVjaXBlc3xlbnwwfHwwfHx8MA%3D%3D",
    }
  ];
  
  export default blogPost;